+ source activate /N/u/jmelms/Quartz/envs/earth2mip
++ _CONDA_ROOT=/N/slate/jmelms/software/bigred200/miniconda3
++ . /N/slate/jmelms/software/bigred200/miniconda3/etc/profile.d/conda.sh
+++ export CONDA_EXE=/N/slate/jmelms/software/bigred200/miniconda3/bin/conda
+++ CONDA_EXE=/N/slate/jmelms/software/bigred200/miniconda3/bin/conda
+++ export _CE_M=
+++ _CE_M=
+++ export _CE_CONDA=
+++ _CE_CONDA=
+++ export CONDA_PYTHON_EXE=/N/slate/jmelms/software/bigred200/miniconda3/bin/python
+++ CONDA_PYTHON_EXE=/N/slate/jmelms/software/bigred200/miniconda3/bin/python
+++ '[' -z x ']'
++ conda activate /N/u/jmelms/Quartz/envs/earth2mip
++ local cmd=activate
++ case "$cmd" in
++ __conda_activate activate /N/u/jmelms/Quartz/envs/earth2mip
++ '[' -n '' ']'
++ local ask_conda
+++ PS1=
+++ __conda_exe shell.posix activate /N/u/jmelms/Quartz/envs/earth2mip
+++ /N/slate/jmelms/software/bigred200/miniconda3/bin/conda shell.posix activate /N/u/jmelms/Quartz/envs/earth2mip

EnvironmentLocationNotFound: Not a conda environment: /N/u/jmelms/Quartz/envs/earth2mip

++ ask_conda=
++ return
+ echo 'Beginning inference script'
+ python run_inference.py
/geode2/home/u040/jmelms/BigRed200/envs/earth2mip/lib/python3.10/site-packages/gribapi/__init__.py:23: UserWarning: ecCodes 2.31.0 or higher is recommended. You are running version 2.30.0
  warnings.warn(
Traceback (most recent call last):
  File "/geode2/home/u040/jmelms/BigRed200/projects/dynamical-tests-FCN/code/earth2mip-main/models/fcnv2_sm/run_inference.py", line 6, in <module>
    run_custom_inference(
  File "/geode2/home/u040/jmelms/BigRed200/projects/dynamical-tests-FCN/code/earth2mip-main/models/fcnv2_sm/inference_utils.py", line 203, in run_custom_inference
    package, sfno_inference_model, data_source = _setup(
  File "/geode2/home/u040/jmelms/BigRed200/projects/dynamical-tests-FCN/code/earth2mip-main/models/fcnv2_sm/inference_utils.py", line 37, in _setup
    sfno_inference_model = fcnv2_sm_load(package, device=device)
  File "/N/project/obrienta_startup/wxmod_ai/earth2mip/earth2mip/networks/fcnv2_sm.py", line 151, in load
    local_center = np.load(package.get("global_means.npy"))
  File "/geode2/home/u040/jmelms/BigRed200/envs/earth2mip/lib/python3.10/site-packages/numpy/lib/npyio.py", line 427, in load
    fid = stack.enter_context(open(os_fspath(file), "rb"))
FileNotFoundError: [Errno 2] No such file or directory: '/N/u/jmelms/Quartz/.cache/earth2mip/models/fcnv2_sm/global_means.npy'
+ echo 'Inference script complete'
